# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/188QDpcZ-dBUFXCvSmlSaR8OKkttqeb-H
"""

import re

import pandas as pd

file = pd.read_csv("https://raw.githubusercontent.com/viniciusrpb/cic0269_natural_language_processing/main/diario_oficial_pref_sp/dosp_29012016.csv")

file

t = file.iloc[:7,6]
t

titles = []
processes = []
values = []

for line in t:
  title = re.findall(r"..TITULO..(.*)\s*..TEXTO..", line)
  print(title)
  titles.append(title[0])

for line in t:
  process = re.findall(r".*.SEI(.*)..CL..", line)
  if(process == []):
    process.append("NaN")
  print(process)
  processes.append(process[0])

for line in t:
  value = re.findall(r".*VALOR GLOBAL.*..CL....(..........)", line)
  if(value == []):
    value.append("NaN")
  print(value)
  values.append(value[0])

list = []

for i in range(t.size):
  list.append([titles[i], processes[i], values[i]])

df = pd.DataFrame(list, columns = ['Título', 'Número do Processo', 'Valor'])

df

